### ISSUE TITLE
Training code for StealthTshirt

### ISSUE THREAD

**Issue by XiaodanLi001** [advboxes/AdvBox#37]
Hi, thank you for your contribution. Are you going to release codes for generating Defcon_Sticker.png? Or , can you share the way to generate Defcon_Sticker.png?

**Comment by saddenlar** [comment]
> Hi, thank you for your contribution. Are you going to release codes for generating Defcon_Sticker.png? Or , can you share the way to generate Defcon_Sticker.png?

Hi XiaodanLi001,

Yes, we will be releasing our tool-box for generating such adversarial stickers in recent days. We will hold a tutorial talk on HITB CommSec Track on 29 Aug 2019. They will provide youtube live.

https://gsec.hitb.org/sg2019/sessions/commsec-hacking-object-detectors-is-just-like-training-neural-networks/.

Hope you enjoy!

**Comment by XiaodanLi001** [comment]
> > Hi, thank you for your contribution. Are you going to release codes for generating Defcon_Sticker.png? Or , can you share the way to generate Defcon_Sticker.png?
> 
> Hi XiaodanLi001,
> 
> Yes, we will be releasing our tool-box for generating such adversarial stickers in recent days. We will hold a tutorial talk on HITB CommSec Track on 29 Aug 2019. They will provide youtube live.
> 
> https://gsec.hitb.org/sg2019/sessions/commsec-hacking-object-detectors-is-just-like-training-neural-networks/.
> 
> Hope you enjoy!

Looking forward to it.

**Comment by lea4n** [comment]
Great job!

**Comment by vtddggg** [comment]
Great job!
