### ISSUE TITLE
TypeError: Can't instantiate abstract class EOTB_attack with abstract methods interpret_output

### ISSUE THREAD

**Issue by kqvd** [advboxes/AdvBox#60]
I'm trying to run the ODD code via attack_model.py, but I'm getting this error:

2020-09-18 07:24:08.108889: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "attack_model.py", line 23, in <module>
    main(sys.argv)
  File "attack_model.py", line 18, in main
    attack = EOTB_attack(YOLO_tiny_model_updated)
TypeError: Can't instantiate abstract class EOTB_attack with abstract methods interpret_output

**Comment by jayxio** [comment]
Could you provide us with more info? like what was the command using then etc?

**Comment by kqvd** [comment]
"python attack_model.py -fromfile data_sampling -frommaskfile test/EOTB.xml"

I've tried running it on Google Colab and also Spyder from Anaconda.

**Comment by jayxio** [comment]
Could you try to delete the `_` which is at the beginning of the EOTB_attack method, `_interpret_output`? It might be that the name is inconsistent with the name in (an abstractmethod) ODD_logic.

**Comment by kqvd** [comment]
Thanks, it's progressed now!

I'm not sure what happens here as the code stops in this line in basic_logic.py. Do I have to enter something or press a key?

![Screenshot 2020-09-18 193511](https://user-images.githubusercontent.com/37205677/93582621-177bb900-f9e6-11ea-9c67-3d0ae4008ede.png)

![Screenshot 2020-09-18 193543](https://user-images.githubusercontent.com/37205677/93582680-295d5c00-f9e6-11ea-99a9-13caa07b5423.png)

**Comment by kqvd** [comment]
Thanks, it's working now!

It's sent me

**Comment by kqvd** [comment]
Nevermind, I need to comment out the pdb.set_trace()
