### ISSUE TITLE
ODD Effectiveness

### ISSUE THREAD

**Issue by kqvd** [advboxes/AdvBox#63]
Hi, I'm trying to replicate the Defcon_Sticker.png from Object Detector Deception.

In your example, what values did you input for the attack steps and hyperparameter variables for punishment and smoothness? Also, how many images were added in the data sampling folder?

I have a dataset of 2000 images I want to use for training the attack model.

Thank you.

**Comment by jayxio** [comment]
I remember the attack steps is around 400, as for the other hyperparameters, I just used the default value(in the repo you can see them). 
Around 3000 images(all contain high confidence people target in them) were used for the attack process.
