### ISSUE TITLE
Can StealthTshirt be used for generating new adversarial patches?

### ISSUE THREAD

**Issue by cyber-ranger** [advboxes/AdvBox#84]
It looks like /applications/StealthTshirt/StealthTshirtDemo.py only provides the YOLO OD demo. Is there only one patch (Defcon_Sticker.png) can be used for physical adversarial attack?
How can I use AdvBox for generating more adversarial patches? THX

**Comment by jayxio** [comment]
We've recently been working on a new project https://github.com/PaddlePaddle/PaddleSleeve/tree/main/AdvBox. It contains a digital attack demo for object detectors based on the PaddleDetection project. 

Check out `Adversarial Perturbation for Object Detection` section. You can generate new patches based on the new object detector provided by PaddleDetection. Physical attack is developing.
